delete from zoo
insert into zoo values (	1	,	3	)
insert into zoo values (	1	,	6	)
insert into zoo values (	1	,	7	)
insert into zoo values (	2	,	2	)
insert into zoo values (	2	,	4	)
insert into zoo values (	2	,	8	)
insert into zoo values (	3	,	4	)
insert into zoo values (	3	,	1	)
insert into zoo values (	3	,	9	)
insert into zoo values (	5	,	2	)
insert into zoo values (	5	,	5	)
insert into zoo values (	5	,	7	)
insert into zoo values (	6	,	1	)
insert into zoo values (	6	,	4	)
insert into zoo values (	6	,	7	)
insert into zoo values (	7	,	5	)
insert into zoo values (	7	,	3	)
insert into zoo values (	8	,	9	)
insert into zoo values (	7	,	8	)
insert into zoo values (	8	,	5	)
insert into zoo values (	8	,	2	)
insert into zoo values (	9	,	7	)
insert into zoo values (	9	,	5	)
insert into zoo values (	9	,	3	)
      